# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 22:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('current_token', models.CharField(max_length=200)),
                ('refresh_token', models.CharField(max_length=200)),
                ('token_expires_at', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Credentials',
            },
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('code', models.UUIDField(unique=True)),
                ('odometer_start', models.IntegerField(blank=True, default=None, null=True)),
                ('odometer_end', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked', models.BooleanField(verbose_name='False if the credentials were removed or the vehicle is not listed anymore')),
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('vehicle_id', models.BigIntegerField()),
                ('display_name', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=200)),
                ('vin', models.CharField(max_length=17)),
                ('state', models.CharField(max_length=200)),
                ('credentials', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teslarent.Credentials')),
            ],
        ),
        migrations.AddField(
            model_name='rental',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teslarent.Vehicle'),
        ),
    ]
