# Generated by Django 2.1.9 on 2019-09-07 15:30

from django.db.models import JSONField
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('salt', models.CharField(max_length=16, verbose_name='Salt for KDF from secret to encryption key')),
                ('iv', models.CharField(max_length=32, verbose_name='Initialization Vector for token encryption')),
                ('current_token', models.CharField(max_length=512)),
                ('refresh_token', models.CharField(max_length=512)),
                ('token_expires_at', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Credentials',
            },
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('code', models.UUIDField(unique=True)),
                ('odometer_start', models.IntegerField(blank=True, default=None, null=True)),
                ('odometer_start_updated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('odometer_end', models.IntegerField(blank=True, default=None, null=True)),
                ('odometer_end_updated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('price_brutto', models.FloatField(blank=True, default=None, null=True)),
                ('price_netto', models.FloatField(blank=True, default=None, null=True)),
                ('price_charging', models.FloatField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked', models.BooleanField(verbose_name='False if the credentials were removed or the vehicle is not listed anymore')),
                ('tesla_id', models.BigIntegerField(blank=True, default=None, null=True)),
                ('vehicle_id', models.BigIntegerField()),
                ('display_name', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=200)),
                ('vin', models.CharField(max_length=17)),
                ('state', models.CharField(max_length=200)),
                ('mobile_enabled', models.BooleanField(null=True)),
                ('option_codes', models.CharField(blank=True, max_length=500, null=True)),
                ('credentials', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teslarent.Credentials')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', JSONField()),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teslarent.Vehicle')),
            ],
            options={
                'verbose_name_plural': 'Vehicle Data',
            },
        ),
        migrations.AddField(
            model_name='rental',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teslarent.Vehicle'),
        ),
    ]
