# Generated by Django 2.1.7 on 2019-05-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teslarent', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicledata',
            options={'verbose_name_plural': 'Vehicle Data'},
        ),
        migrations.AddField(
            model_name='rental',
            name='price_brutto',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='price_charging',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='price_netto',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
