# Generated by Django 3.1.2 on 2022-02-16 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teslarent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentials',
            name='refresh_token',
            field=models.CharField(max_length=2048),
        ),
    ]
