# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('teslarent', '0002_auto_20170221_1246'), ('teslarent', '0003_vehicle_mobile_enabled')]

    dependencies = [
        ('teslarent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='odometer_end_updated_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='odometer_start_updated_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='mobile_enabled',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
