# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teslarent', '0002_auto_20170221_1246_squashed_0003_vehicle_mobile_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentials',
            name='iv',
            field=models.CharField(default='', max_length=32, verbose_name='Initialization Vector for token encryption'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='credentials',
            name='salt',
            field=models.CharField(default='', max_length=16, verbose_name='Salt for KDF from secret to encryption key'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='credentials',
            name='current_token',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='credentials',
            name='refresh_token',
            field=models.CharField(max_length=512),
        ),
    ]
