# Generated by Django 2.1.7 on 2019-05-26 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teslarent', '0002_auto_20190526_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='price_charging',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
