# Generated by Django 2.1.9 on 2019-08-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teslarent', '0004_auto_20190811_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='option_codes',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
