# Generated by Django 2.1.9 on 2019-08-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teslarent', '0005_vehicle_option_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='model',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='option_codes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
